import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Providers from "./StoreProvider";
import { UIProvider } from "./UIProvider";

const inter = Lato({ subsets: ["latin"], weight: ["400","700","900"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <UIProvider>
            <div className="px-[22px] bg-[#333333] overflow-hidden w-screen h-screen max-w-screen max-h-screen">
              {children}
            </div>
          </UIProvider>
        </Providers>
      </body>
    </html>
  );
}
